[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm --prefix web-app install"]

[phases.build]
cmds = ["npm --prefix web-app run build"]

[start]
cmd = "npx -y serve -s web-app/dist -l ${PORT:-8080}"
