[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd web-app && NPM_CONFIG_PRODUCTION=false npm install --include=optional --include=dev"]

[phases.build]
cmds = ["cd web-app && NPM_CONFIG_PRODUCTION=false npm run build"]

[start]
cmd = "npx -y serve -s web-app/dist -l ${PORT:-8080}"
